### ISSUE TITLE
The C# script in Lesson02

### ISSUE THREAD

**Issue by txhsl** [alienworks/InteractiveTutorial-Lessons#21]
- https://github.com/alienworks/InteractiveTutorial-Lessons/blob/06c5a3e5bac21e69ff22a12142292a44c4ccefd1/C%23/en-us/Lesson02/AlienFinder-L2.cs#L35 Use `Id = ++counter` if the id is supposed to start from 1.
- https://github.com/alienworks/InteractiveTutorial-Lessons/blob/06c5a3e5bac21e69ff22a12142292a44c4ccefd1/C%23/en-us/Lesson02/AlienFinder-L2.cs#L95 The method `Mutate` does't update xna randomly, because the first few figures are rarely changed in practice. And I'm wondering the meaning of `attribute` here.

@merlin217 .

**Comment by merlin217** [comment]
c8eb2f20965d093e94a8ff9173cc026042560f35

Just fixed `counter` and updated the Mutate() description as below: 
https://github.com/alienworks/InteractiveTutorial-Lessons/blob/c8eb2f20965d093e94a8ff9173cc026042560f35/C%23/en-us/Lesson02/AlienFinder-L2.cs#L93-L97

`mutate()` may still be subject to update in the future as I am still unsure if it's better to simply write a more generic `ChangeAttribute(byte[] id, uint attribute, int changeAmount)` inside the class and let the game handle rng logic.
